apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "k8s-mediaserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-mediaserver.selectorLabels" . | nindent 8 }}
        app: jackett
    spec:
      initContainers:
        - name: config-jackett
          image: docker.io/ubuntu:groovy
          command: ["/init-jackett/init-jackett.sh"]
          volumeMounts:
            - mountPath: /init-jackett
              name: init-files-jackett
            - mountPath: /jackett-config
              name: mediaserver-volume
              subPath: "config/jackett/Jackett"
          securityContext:
            runAsUser: {{ .Values.general.puid }}
            runAsGroup: {{ .Values.general.pgid }}
      containers:
        - name: {{ .Chart.Name }}
          envFrom:
            - configMapRef:
                name: jackett-config
          image: docker.io/linuxserver/jackett:{{ .Values.general.image_tag }}
          imagePullPolicy: Always
          readinessProbe:
            tcpSocket:
              port: {{ .Values.jackett.container.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - name: jackett-port
              containerPort: {{ .Values.jackett.container.port }}
              protocol: TCP
          volumeMounts:
            - name: mediaserver-volume
              mountPath: "/config"
              subPath: "config/jackett"
      volumes:
        - name: mediaserver-volume
          persistentVolumeClaim:
            claimName: {{ .Values.general.storage.pvcName }}
        - name: init-files-jackett
          configMap:
            defaultMode: 493
            name: init-jackett-cm
      {{- with .Values.general.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
