{{- if .Values.plex.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
  {{- with .Values.plex.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{ if .Values.plex.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.general.plex_ingress_host | quote }}
      secretName: {{ .Values.plex.ingress.tls.secretName }}
{{ end }}     
  rules:
    - host: {{ .Values.general.plex_ingress_host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plex
                port:
                  number: {{ .Values.plex.service.port }}
{{ end }}     
