apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "k8s-mediaserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-mediaserver.selectorLabels" . | nindent 8 }}
        app: radarr
    spec:
      initContainers:
        - name: config-radarr
          image: docker.io/ubuntu:groovy
          command: ["/init-radarr/init-radarr.sh"]
          volumeMounts:
            - mountPath: /init-radarr
              name: init-files-radarr
            - mountPath: /radarr-config
              name: mediaserver-volume
              subPath: "config/radarr"
          securityContext:
            runAsUser: {{ .Values.general.puid }}
            runAsGroup: {{ .Values.general.pgid }}
      containers:
        - name: {{ .Chart.Name }}
          envFrom:
            - configMapRef:
                name: radarr-config
          image: "docker.io/linuxserver/radarr:{{ .Values.general.image_tag }}"
          imagePullPolicy: Always
          readinessProbe:
            tcpSocket:
              port: {{ .Values.radarr.container.port }}
            initialDelaySeconds: 10
            periodSeconds: 20
          ports:
            - name: radarr-port
              containerPort: {{ .Values.radarr.container.port }}
              protocol: TCP
          volumeMounts:
            - name: mediaserver-volume
              mountPath: "/config"
              subPath: "config/radarr"
            - name: mediaserver-volume
              mountPath: "/downloads"
              subPath: "downloads/transmission"
            - name: mediaserver-volume
              mountPath: "/movies"
              subPath: "media/movies"
      volumes:
        - name: mediaserver-volume
          persistentVolumeClaim:
            claimName: {{ .Values.general.storage.pvcName }}
        - name: init-files-radarr
          configMap:
            defaultMode: 493
            name: init-radarr-cm
      {{- with .Values.general.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
